<?php

namespace AppBundle\Repository;
use AppBundle\Entity\Cidade;
use AppBundle\Entity\Endereco;
use AppBundle\Entity\Estado;
use Doctrine\ORM\EntityRepository;

/**
 * CidadeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CidadeRepository extends EntityRepository
{
    public function loadByIdEstado($idEstado)
    {

        $qb = $this->createQueryBuilder('c')
            ->where('c.estado = :idEstado')
            ->setParameter('idEstado', $idEstado)
            ->getQuery()
            ->getArrayResult();

        return $qb;

    }

    public function loadEnderecoExisteLoja()
    {

        $qb  =   $this->getEntityManager()->createQueryBuilder()
            ->select('distinct(e.cidade) as idCidade, e.bairro, c.cidade, es.estado, es.sigla, es.id as idEstado')
            ->from(Endereco::class, 'e')
            ->leftJoin(Cidade::class, 'c', 'WITH', "c.id = e.cidade")
            ->leftJoin(Estado::class, 'es', 'WITH', "es.id = c.estado")
            ->getQuery()
            ->getArrayResult();

        return $qb;

    }

}