<?php

namespace AppBundle\Repository;
use AppBundle\Entity\Cidade;
use AppBundle\Entity\Endereco;
use AppBundle\Entity\Estado;
use Doctrine\ORM\EntityRepository;
use AppBundle\Entity\Status;

/**
 * LojaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LojaRepository extends EntityRepository
{


    public function listarDados($aColumns, $sWhere, $request) {

        $query  =  $this->createQueryBuilder('l')
            ->select('l.id', 's.nome as nomeStatus', 'l.nome', 'l.razaoSocial',
                'CONCAT(e.endereco, \' - \', c.cidade, \' - \', es.sigla) AS endereco',
                'CONCAT(l.telefone1, \' - \',l.telefone2) AS telefone')
            ->leftJoin(Status::class, 's', 'WITH', "l.status = s.id")
            ->leftJoin(Endereco::class, 'e', 'WITH', "l.endereco = e.id")
            ->leftJoin(Cidade::class, 'c', 'WITH', "c.id = e.cidade")
            ->leftJoin(Estado::class, 'es', 'WITH', "es.id = c.estado");

        $iDisplayStart = $request->get('start');
        $iDisplayLength = $request->get('length');

        //echo $query->where($sWhere); exit;
        if (empty($sWhere)) {
            return $query->getMaxResults($iDisplayLength)->setFirstResult($iDisplayLength)->getQuery()->getArrayResult();
        }

        $result = $query->where($sWhere)
            ->setMaxResults($iDisplayLength)
            ->setFirstResult($iDisplayStart)
            ->getQuery()
            ->getArrayResult();

        return $result;

    }

    public function totalRegistroFiltro() {

        return $this->createQueryBuilder('l')
              ->select('count(l)')
              ->getQuery()->getSingleScalarResult();

    }

}