<?php

namespace AppBundle\Repository;
use Doctrine\ORM\EntityRepository;

/**
 * MenuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MenuRepository extends EntityRepository
{
    public function verificaUrlPermitidasPorPerfil($idPerfil)
    {
        return $this->createQueryBuilder('m')
            ->Join('m.perfis', 'p')
            ->where('p.id = :idPerfil')
            ->addOrderBy('m.ordem', 'asc')
            ->setParameter('idPerfil', $idPerfil)
            ->getQuery()
            ->getArrayResult();
    }


}