<?php

namespace AppBundle\Repository;
use AppBundle\Entity\Marca;
use AppBundle\Entity\Produto;
use AppBundle\Entity\TipoProduto;
use Doctrine\ORM\EntityRepository;

/**
 * ProdutoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProdutoRepository extends EntityRepository
{
    public function listarDados($aColumns, $sWhere, $request) {

        $fields = array('p.id', 'tp.nome as nomeTipoProduto', 'm.nome as marcaProduto', 'p.nome as nomeProduto', 'p.descricao');

        $query  =  $this->getEntityManager()->createQueryBuilder()
            ->select($fields)
            ->from(Produto::class, 'p')
            ->leftJoin(TipoProduto::class, 'tp', 'WITH', "p.tipoProduto = tp.id")
            ->leftJoin(Marca::class, 'm', 'WITH', "p.marca = m.id");


        //echo $query->getQuery()->getSQL(); exit;

        $iDisplayStart = $request->get('start');
        $iDisplayLength = $request->get('length');

        //echo $query->where($sWhere); exit;
        if (empty($sWhere)) {
            return $query->getMaxResults($iDisplayLength)->setFirstResult($iDisplayLength)->getQuery()->getArrayResult();
        }

        $result = $query->where($sWhere)
            ->setMaxResults($iDisplayLength)
            ->setFirstResult($iDisplayStart)
            ->getQuery()
            ->getArrayResult();

        return $result;

    }

    public function totalRegistroFiltro() {

        return $this->createQueryBuilder('s')
            ->select('count(s)')
            ->getQuery()->getSingleScalarResult();

    }

}