<?php

namespace AppBundle\Repository;
use AppBundle\Entity\TipoProduto;
use Doctrine\ORM\EntityRepository;

/**
 * TipoProdutoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoProdutoRepository extends EntityRepository
{
    public function listarDados($aColumns, $sWhere, $request) {

        $fields = array('tp.id', 'tp.nome as nomeProduto', 'c.nome as nomeCategoria');

        $query  =  $this->getEntityManager()->createQueryBuilder()
            ->select($fields)
            ->from(TipoProduto::class, 'tp')
            ->leftJoin('tp.categoria', 'c');

        //echo $query->getQuery()->getSQL(); exit;

        $iDisplayStart = $request->get('start');
        $iDisplayLength = $request->get('length');

        //echo $query->where($sWhere); exit;
        if (empty($sWhere)) {
            return $query->getMaxResults($iDisplayLength)->setFirstResult($iDisplayLength)->getQuery()->getArrayResult();
        }

        $result = $query->where($sWhere)
            ->setMaxResults($iDisplayLength)
            ->setFirstResult($iDisplayStart)
            ->getQuery()
            ->getArrayResult();

        return $result;

    }

    public function totalRegistroFiltro() {

        return $this->createQueryBuilder('s')
            ->select('count(s)')
            ->getQuery()->getSingleScalarResult();

    }

    public function loadByIdCategoria($idCategoria)
    {

        $qb = $this->createQueryBuilder('t')
            ->where('t.categoria = :idCategoria')
            ->setParameter('idCategoria', $idCategoria)
            ->getQuery()
            ->getArrayResult();

        return $qb;

    }

}