<?php

namespace AppBundle\Repository;
use Doctrine\ORM\EntityRepository;
use Symfony\Bridge\Doctrine\Security\User\UserLoaderInterface;
use AppBundle\Entity\Status;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsuarioRepository extends EntityRepository implements UserLoaderInterface
{
    public function loadUserByUsername($username)
    {
        return $this->createQueryBuilder('u')
            ->where('u.username = :username OR u.email = :email')
            ->setParameter('username', $username)
            ->setParameter('email', $username)
            ->getQuery()
            ->getOneOrNullResult();

    }

    public function listarDados($aColumns, $sWhere, $request) {

        $query  =  $this->createQueryBuilder('u')
            ->select('u.id', 's.nome as nomeStatus', 'u.nome', 'u.username', 'u.cpf', 'u.email', 'u.dtCadastro')
            ->leftJoin(Status::class, 's', 'WITH', "u.status = s.id");

        $iDisplayStart = $request->get('start');
        $iDisplayLength = $request->get('length');

        //echo $query->where($sWhere); exit;
        if (empty($sWhere)) {
            return $query->getMaxResults($iDisplayLength)->setFirstResult($iDisplayLength)->getQuery()->getArrayResult();
        }

        $result = $query->where($sWhere)
            ->setMaxResults($iDisplayLength)
            ->setFirstResult($iDisplayStart)
            ->getQuery()
            ->getArrayResult();

        return $result;

    }

    public function totalRegistroFiltro() {

        return $this->createQueryBuilder('u')
              ->select('count(u)')
              ->getQuery()->getSingleScalarResult();

    }

}