app:
    resource: '@AppBundle/Controller/'
    type: annotation
    prefix:  /busqueaquisuplementos


topoformbusca:
    path: /
    defaults:
        _controller: 'AppBundle\Controller\DefaultController::carregaBuscaAvancadaFormAction'
        template:    frontend/topoformbusca.html.twig